In [1]:
import pandas as pd
import numpy as np

In [2]:
pdf=pd.read_csv('products.csv')
cdf=pd.read_csv('copurchase.csv')

In [3]:
pdf

id                                              title group  \
0            1            Patterns of Preaching: A Sermon Sampler  Book   
1            2                         Candlemas: Feast of Flames  Book   
2            3   World War II Allied Fighter Planes Trading Cards  Book   
3            4  Life Application Bible Commentary: 1 and 2 Tim...  Book   
4            5    Prayers That Avail Much for Business: Executive  Book   
...        ...                                                ...   ...   
259162  262104                                      Satchel Paige  Book   
259163  262106  Japanese for Busy People: English Teacher's Ma...  Book   
259164  262107                                       Halloween II   DVD   
259165  262108                               Book Of Vision Quest  Book   
259166  262109  Favorite Russian Fairy Tales (Dover Children's...  Book   

        salesrank  review_cnt  downloads  rating  
0        396585.0           2          2     5.0  
1        168596.0          12         12     4.5  
2       1270652.0           1          1     5.0  
3        631289.0           1          1     4.0  
4        455160.0           0          0     0.0  
...           ...         ...        ...     ...  
259162    36449.0           3          3     4.5  
259163   588715.0           0          0     0.0  
259164    31245.0         320        320     4.0  
259165   255390.0           4          4     4.0  
259166   250544.0           2          2     5.0  

[259167 rows x 7 columns]

In [4]:
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259167 entries, 0 to 259166
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   id          259167 non-null  int64  
 1   title       259167 non-null  object 
 2   group       259167 non-null  object 
 3   salesrank   259167 non-null  float64
 4   review_cnt  259167 non-null  int64  
 5   downloads   259167 non-null  int64  
 6   rating      259167 non-null  float64
dtypes: float64(2), int64(3), object(2)
memory usage: 13.8+ MB


In [5]:
pdf.describe()

id     salesrank     review_cnt      downloads  \
count  259167.000000  2.591670e+05  259167.000000  259167.000000   
mean   131018.343813  4.955061e+05      14.000895      13.750589   
std     75663.758316  5.750585e+05      72.878967      69.013924   
min         1.000000 -1.000000e+00       0.000000       0.000000   
25%     65489.500000  9.191100e+04       0.000000       0.000000   
50%    131007.000000  3.031550e+05       2.000000       2.000000   
75%    196511.500000  6.778710e+05       8.000000       7.000000   
max    262109.000000  3.793303e+06    5545.000000    4995.000000   

              rating  
count  259167.000000  
mean        3.158454  
std         2.019447  
min         0.000000  
25%         0.000000  
50%         4.000000  
75%         5.000000  
max         5.000000

In [6]:
pdf['group'].unique()

array(['Book', 'Music', 'DVD', 'Video', 'Toy', 'Video Games', 'Software',
       'Baby Product', 'CE'], dtype=object)

In [7]:
new_pdf=pdf[pdf['group']=='Book']

In [8]:
new_pdf

id                                              title group  \
0            1            Patterns of Preaching: A Sermon Sampler  Book   
1            2                         Candlemas: Feast of Flames  Book   
2            3   World War II Allied Fighter Planes Trading Cards  Book   
3            4  Life Application Bible Commentary: 1 and 2 Tim...  Book   
4            5    Prayers That Avail Much for Business: Executive  Book   
...        ...                                                ...   ...   
259160  262102  The Everything Homebuying Book: From Open Hous...  Book   
259162  262104                                      Satchel Paige  Book   
259163  262106  Japanese for Busy People: English Teacher's Ma...  Book   
259165  262108                               Book Of Vision Quest  Book   
259166  262109  Favorite Russian Fairy Tales (Dover Children's...  Book   

        salesrank  review_cnt  downloads  rating  
0        396585.0           2          2     5.0  
1        168596.0          12         12     4.5  
2       1270652.0           1          1     5.0  
3        631289.0           1          1     4.0  
4        455160.0           0          0     0.0  
...           ...         ...        ...     ...  
259160   664919.0           3          3     4.5  
259162    36449.0           3          3     4.5  
259163   588715.0           0          0     0.0  
259165   255390.0           4          4     4.0  
259166   250544.0           2          2     5.0  

[188013 rows x 7 columns]

In [9]:
new_pdf.group.unique()

array(['Book'], dtype=object)

In [10]:
book_ids=pdf[pdf['group']=='Book']['id'].to_numpy()
book_ids

array([     1,      2,      3, ..., 262106, 262108, 262109])

In [11]:
non_book_ids=pdf[pdf['group']!='Book']['id'].to_numpy()
non_book_ids

array([     7,     14,     18, ..., 262101, 262103, 262107])

In [12]:
len(new_pdf)

188013

In [13]:
len(pdf)

259167

In [14]:
cdf

Source  Target
0             1       2
1             1       4
2             1       5
3             1      15
4             2      11
...         ...     ...
1234865  262110  262099
1234866  262110  262100
1234867  262110  262101
1234868  262110  262106
1234869  262110  262107

[1234870 rows x 2 columns]

In [15]:
len(cdf)

1234870

In [16]:
new_cdf=cdf[cdf.Source.isin(book_ids)]

In [17]:
new_cdf=new_cdf[new_cdf.Target.isin(book_ids)]

In [18]:
new_cdf

Source  Target
0             1       2
1             1       4
2             1       5
3             1      15
4             2      11
...         ...     ...
1234859  262108  262109
1234860  262109  262076
1234861  262109  262097
1234863  262109  262099
1234864  262109  262100

[637893 rows x 2 columns]

In [19]:
len(new_cdf)

637893

In [21]:
new_cdf.Source.isin(book_ids).unique()

array([ True])

In [22]:
new_cdf.Target.isin(book_ids).unique()

array([ True])

In [23]:
# All the edges and nodes are related with BOOK

In [25]:
# producing book related datasets
# new_pdf.to_csv('books_info.csv')
# new_cdf.to_csv('books_copurchase.csv')

In [31]:
# no. of nodes
len(new_pdf)

188013

In [27]:
# no. of edges
len(new_cdf)

637893

In [65]:
in_degree=pd.DataFrame(new_cdf.groupby(['Target'])['Source'].size()).reset_index()
in_degree.columns=['id','in_degree']

out_degree=pd.DataFrame(new_cdf.groupby(['Source'])['Target'].size()).reset_index()
out_degree.columns=['id','out_degree']

all_degree=pd.merge(in_degree,out_degree,on='id',how='outer')
all_degree[np.isnan(all_degree)]=0

all_degree['all_degree']=(all_degree.in_degree+all_degree.out_degree)

all_degree=all_degree.sort_values('all_degree',ascending=False)

all_degree

id  in_degree  out_degree  all_degree
10063    14949      309.0         3.0       312.0
3087      4429      278.0         3.0       281.0
25          33      262.0         4.0       266.0
8624     12771      240.0         3.0       243.0
4            8      201.0         3.0       204.0
...        ...        ...         ...         ...
179775  144940        0.0         1.0         1.0
154841  230770        1.0         0.0         1.0
111772  164783        1.0         0.0         1.0
12185    18013        1.0         0.0         1.0
145149  215939        1.0         0.0         1.0

[186147 rows x 4 columns]

In [56]:
# len(all_degree)

186147

In [66]:
# node with highest all_degree
new_pdf[new_pdf['id']==14849]

id                                              title group  \
14707  14849  McCoy Pottery: Reference & Value Guide (McCoy ...  Book   

       salesrank  review_cnt  downloads  rating  
14707   159827.0          11         11     4.5